---
title: "drew_notes"
author: "Drew Faturos"
date: "11/8/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(randomForest)
source("practice_data.R")

```
 playing with randomForest package 
 

 
 
```{r playing with Random forest tutorial}
require(MASS)
attach(Boston)
set.seed(101)
dim(Boston)

#train sample 
train=sample(1:nrow(Boston),300)

#for tutorial using medv as the response variable 
#and using 500 trees, medv(median house value).
#using all other variables as predictor variables 

Boston.rf=randomForest(medv ~ . , data = Boston , subset = train)
Boston.rf

plot(Boston.rf)

?randomForest
```

vignette("randomForest")


```{r tutorial from help file }

data(iris)
?set.seed
#running ranndomForest Code
iris.rf <- randomForest(Species ~ ., data=iris,
                        importance=TRUE, proximity=TRUE)
View(iris)
print(iris.rf)

#looking at variable importance 
round(importance(iris.rf), 2)

## Do MDS on 1 - proximity:
iris.mds <- cmdscale(1 - iris.rf$proximity, eig=TRUE)
op <- par(pty="s")
pairs(cbind(iris[,1:4], iris.mds$points), cex=0.6, gap=0,
      col=c("red", "green", "blue")[as.numeric(iris$Species)],
      main="Iris Data: Predictors and MDS of Proximity Based on RandomForest")
par(op)

print(iris.mds$GOF)

## Regresion

data("airquality")
set.seed(131)
ozone.rf <- randomForest(Ozone ~ ., data=airquality,
                         mtry=3,importance=TRUE,
                         na.action=na.omit)
print(ozone.rf)

#show importance of variables
#higher value mean more important

round(importance(ozone.rf), 2)


##playing with randomforst variable importance plot

data(mtcars)
mtcars.rf <- randomForest(mpg~ ., data = mtcars, 
                          ntreee = 1000, 
                          keep.forest =FALSE, 
                          importance = TRUE)
varImpPlot(mtcars.rf)

```



















```{r importing example from excel and making graphs}
cmax <- read_excel("data/DRUG_CLASS_I_Mean_Cmax_Trough_Efficacy_R_DATA_ANALYSIS.xlsx",
                   sheet = "Mean_PK_Efficacy_In vitro", skip = 1, n_max = 12)

trough <- read_excel("data/DRUG_CLASS_I_Mean_Cmax_Trough_Efficacy_R_DATA_ANALYSIS.xlsx",
                     sheet = "Mean_PK_Efficacy_In vitro", skip = 16, n_max = 12)
# grouping by ELU
cmax_group <- gather(cmax, key= outcome, value = value_outcome, ELU:ESP)

group_test <- gather(cmax_group, key = variable, value = value_variable, PLA:SLE)

group_test%>% 
  #filter(outcome =="ESP") %>% 
  mutate(value_variable = as.numeric(value_variable)) %>% 
  ggplot()+
  geom_histogram(aes( x = value_variable))+
  facet_wrap(~variable)

str(group_test)





```

